apiVersion: 1

datasources:
  - name: ClickHouse_IoT_DW
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    jsonData:
      defaultDatabase: iot_telemetry
      port: 8123
      server: clickhouse
      username: iot_admin
    secureJsonData:
      password: iot_password
    isDefault: true
    editable: true